# Generated by Django 4.0.1 on 2022-01-19 22:34


from functools import lru_cache
import csv
import string
from django.db import migrations
from main.utils import transform_text

@lru_cache(maxsize=None)
def get_sector(sector_model, sector):
    s, _ = sector_model.objects.get_or_create(name=sector)
    return s

def insert_policy(policy_model, sector_model, l: str):
    _id, title, sectors, text = l
    words_only_text = transform_text(text)
    unique_words = ' '.join(sorted(set(words_only_text.split())))
    sectors = sectors.split(';')
    p = policy_model.objects.create(id=_id,
                          title=title,
                          description_text=text,
                          terms=unique_words)  # migrations don't call custom methods()
    sectors = [get_sector(sector_model, s) for s in sectors]
    p.sectors.set(sectors)
    p.save()

def ingest(apps, schema_editor):
    Policy = apps.get_model('main', 'Policy')
    Sector = apps.get_model('main', 'Sector')
    with open('cpr-task_1-full.csv', encoding='utf-8') as f:
        reader = csv.reader(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        next(reader)
        for l in reader:
            print(l)
            insert_policy(Policy, Sector, l)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
    migrations.RunPython(ingest),
    ]
